#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on:
  push:
    tags:
    - 'v*'

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SMART_DNS: smartdns.sh
  SMART_DNS_LUCI: smartdns-luci.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Add SmartDNS
      run: |
        chmod +x $SMART_DNS
        chmod +x $SMART_DNS_LUCI
        cd openwrt
        ../$SMART_DNS
        ../$SMART_DNS_LUCI
        
    - name: Add Frp Code
      run: |
        git clone https://github.com/kuoruan/openwrt-frp.git package/frp
        
    - name: add passwall package
      run: |
        echo "" >> openwrt/feeds.conf.default
        echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> openwrt/feeds.conf.default
        
    - name: show feeds.conf.default
      run: |
        cat openwrt/feeds.conf.default

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"

    - name: assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade
        path: ./artifact/

    - name: push to tags
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifact/*
        tag: ${{ github.ref }}
        file_glob: true
