#=================================================
# https://github.com/P3TERX/Actions-lede
# Description: Build lede using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build lede

on:
  push:
    tags:
    - 'l*'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SMART_DNS: smartdns.sh
  SMART_DNS_LUCI: smartdns-luci.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo apt-get -y purge git
        sudo apt-get -y install git

    - name: show disk left
      run: |
        df -lh

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede

    - name: Add SmartDNS
      run: |
        chmod +x $SMART_DNS
        chmod +x $SMART_DNS_LUCI
        cd lede
        ../$SMART_DNS
        ../$SMART_DNS_LUCI
        
    - name: Add Frp Code
      run: |
        git clone https://github.com/kuoruan/openwrt-frp.git package/frp
        
    - name: add passwall package
      run: |
        echo "" >> lede/feeds.conf.default
        echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> lede/feeds.conf.default
        echo "" >> lede/feeds.conf.default
        echo "src-git small https://github.com/kenzok8/small" >> lede/feeds.conf.default
        
    - name: show feeds.conf.default
      run: |
        cat lede/feeds.conf.default

    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files lede/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
        chmod +x $DIY_SH
        cd lede
        ../$DIY_SH
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Download package
      id: package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"

    - name: assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./lede/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./lede/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: lede-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade
        path: ./artifact/

    - name: push to tags
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifact/*
        tag: ${{ github.ref }}
        file_glob: true
